export const bosses = [
  {
    name: 'Gargouille vaillante & Gargouille vaillante à la lame double',
    location: 'La Siofra',
    inDlc: false,
    done: false,
  },
  {
    name: 'Soldat draconique',
    location: 'La Siofra',
    inDlc: false,
    done: false,
  },
  {
    name: 'Esprit ancestral',
    location: 'La Siofra',
    inDlc: false,
    done: false,
  },
  {
    name: 'Esprit ancestral royal',
    location: 'La Siofra',
    inDlc: false,
    done: false,
  },
  {
    name: 'Larme imitatrice',
    location: 'La Siofra',
    inDlc: false,
    done: false,
  },
  {
    name: 'Mohg Seigneur du Sang',
    location: 'La Siofra',
    inDlc: false,
    done: false,
  },
  {
    name: 'Soldat draconide de Nokstella',
    location: "Aval de l'Ainsel",
    inDlc: false,
    done: false,
  },
  {
    name: 'Soldat draconide',
    location: "Aval de l'Ainsel",
    inDlc: false,
    done: false,
  },
  {
    name: 'Astel le Rejeton du vide',
    location: "Aval de l'Ainsel",
    inDlc: false,
    done: false,
  },
  {
    name: 'Fortissax la Liche draconique',
    location: 'Profondeurs de Fonderacine',
    inDlc: false,
    done: false,
  },
  {
    name: 'Champions de Fia',
    location: 'Profondeurs de Fonderacine',
    inDlc: false,
    done: false,
  },
  {
    name: 'Siluria du Creuset',
    location: 'Profondeurs de Fonderacine',
    inDlc: false,
    done: false,
  },
  {
    name: "Avatar de l'Arbre-Monde",
    location: 'Profondeurs de Fonderacine',
    inDlc: false,
    done: false,
  },
  {
    name: 'Duo Sanctechair',
    location: 'Ruines de Farum Azula',
    inDlc: false,
    done: false,
  },
  {
    name: 'Placidusax Seigneur Draconique',
    location: 'Ruines de Farum Azula',
    inDlc: false,
    done: false,
  },
  {
    name: "Maliketh la Lame d'ébène",
    location: 'Ruines de Farum Azula',
    inDlc: false,
    done: false,
  },
  {
    name: 'Malenia Épée de Miquella',
    location: 'Arbre-Sacré de Miquella',
    inDlc: false,
    done: false,
  },
  {
    name: "Loretta Chevaleresse de l'Arbre-Sacré",
    location: 'Arbre-Sacré de Miquella',
    inDlc: false,
    done: false,
  },
  {
    name: 'Volatile funéraire (Night)',
    location: 'Cimes des Géants (Ouest)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Astel la Constellation des Ténèbres',
    location: 'Cimes des Géants (Ouest)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Duo de Cavaliers Crépusculaires',
    location: 'Cimes des Géants (Ouest)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Larme imitatrice errante',
    location: 'Cimes des Géants (Ouest)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Duelliste Gardien du Tombeau putride',
    location: 'Cimes des Géants (Ouest)',
    inDlc: false,
    done: false,
  },
  {
    name: "Avatar de l'Arbre-Monde",
    location: 'Cimes des Géants (Ouest)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Chimère léonine',
    location: 'Cimes des Géants (Ouest)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Theodorix le Grand Ver',
    location: 'Cimes des Géants (Ouest)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Cavalier Crépusculaire (Night)',
    location: 'Cimes des Géants (Est)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Gargouille vaillante',
    location: 'Cimes des Géants (Est)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Ancien héros de Zamor',
    location: 'Cimes des Géants (Est)',
    inDlc: false,
    done: false,
  },
  {
    name: "Esprit d'arbre ulcéreux",
    location: 'Cimes des Géants (Est)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Géant de feu',
    location: 'Cimes des Géants (Est)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Volatile funéraire',
    location: 'Cimes des Géants (Est)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Nocher Diaphane',
    location: 'Cimes des Géants (Est)',
    inDlc: false,
    done: false,
  },
  {
    name: "Avatar de l'Arbre-Monde",
    location: 'Cimes des Géants (Est)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Gardien en chef Arghanthy',
    location: 'Cimes des Géants (Est)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Vyke, chevalier de la Table ronde',
    location: 'Cimes des Géants (Est)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Boréalis la Brume Glaciale',
    location: 'Cimes des Géants (Est)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Commandant Niall',
    location: 'Cimes des Géants (Est)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Escargot Mande-Spectre',
    location: 'Cimes des Géants (Est)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Volatile funéraire (Night)',
    location: 'Leyndell, Capitale Royale',
    inDlc: false,
    done: false,
  },
  {
    name: 'Margit le déchu',
    location: 'Leyndell, Capitale Royale',
    inDlc: false,
    done: false,
  },
  {
    name: "Seigneur d'Onyx",
    location: 'Leyndell, Capitale Royale',
    inDlc: false,
    done: false,
  },
  {
    name: "Esprit d'arbre ulcéreux",
    location: 'Leyndell, Capitale Royale',
    inDlc: false,
    done: false,
  },
  {
    name: "Sentinelle draconique de l'Arbre",
    location: 'Leyndell, Capitale Royale',
    inDlc: false,
    done: false,
  },
  {
    name: 'Duelliste Gardien du Tombeau',
    location: 'Leyndell, Capitale Royale',
    inDlc: false,
    done: false,
  },
  {
    name: 'Ordovis Chevalier du Creuset',
    location: 'Leyndell, Capitale Royale',
    inDlc: false,
    done: false,
  },
  {
    name: 'Mohg le réprouvé',
    location: 'Leyndell, Capitale Royale',
    inDlc: false,
    done: false,
  },
  {
    name: "Esprit d'arbre ulcéreux",
    location: 'Leyndell, Capitale Royale',
    inDlc: false,
    done: false,
  },
  {
    name: "Avatar de l'Arbre-Monde",
    location: 'Leyndell, Capitale Royale',
    inDlc: false,
    done: false,
  },
  {
    name: 'Esgar prêtre de sang',
    location: 'Leyndell, Capitale Royale',
    inDlc: false,
    done: false,
  },
  {
    name: 'Morgott roi des Réprouvés',
    location: 'Leyndell, Capitale Royale',
    inDlc: false,
    done: false,
  },
  {
    name: "Godfrey premier Seigneur d'Elden (Gold)",
    location: 'Leyndell, Capitale Royale',
    inDlc: false,
    done: false,
  },
  {
    name: 'Jumeaux Abominables',
    location: 'Leyndell, Capitale Royale',
    inDlc: false,
    done: false,
  },
  {
    name: "Sire Gideon Ofnir l'Omniscient",
    location: 'Leyndell, Capitale des Cendres',
    inDlc: false,
    done: false,
  },
  {
    name: "Godfrey premier Seigneur d'Elden",
    location: 'Leyndell, Capitale des Cendres',
    inDlc: false,
    done: false,
  },
  {
    name: "Radagon de l'Ordre d'or",
    location: 'Leyndell, Capitale des Cendres',
    inDlc: false,
    done: false,
  },
  {
    name: 'Godefroy le greffé',
    location: 'Plateau Altus',
    inDlc: false,
    done: false,
  },
  {
    name: 'Cavalier Crépusculaire (Night)',
    location: 'Plateau Altus',
    inDlc: false,
    done: false,
  },
  {
    name: 'Créature stellaire',
    location: 'Plateau Altus',
    inDlc: false,
    done: false,
  },
  {
    name: 'Les Sentinelles de l’Arbre',
    location: 'Plateau Altus',
    inDlc: false,
    done: false,
  },
  {
    name: 'Tueur de Réprouvés et Miranda',
    location: 'Plateau Altus',
    inDlc: false,
    done: false,
  },
  {
    name: 'Lansseax le dragon ancien',
    location: 'Plateau Altus',
    inDlc: false,
    done: false,
  },
  {
    name: 'Ancien héros de Zamor',
    location: 'Plateau Altus',
    inDlc: false,
    done: false,
  },
  {
    name: 'Assassin des couteaux noirs',
    location: 'Plateau Altus',
    inDlc: false,
    done: false,
  },
  {
    name: 'Crystalians',
    location: 'Plateau Altus',
    inDlc: false,
    done: false,
  },
  {
    name: 'Face de Ver',
    location: 'Plateau Altus',
    inDlc: false,
    done: false,
  },
  {
    name: 'Apôtre Sanctechair',
    location: 'Plateau Altus',
    inDlc: false,
    done: false,
  },
  {
    name: 'Noble Sanglant',
    location: 'Plateau Altus',
    inDlc: false,
    done: false,
  },
  {
    name: 'Makar le Dragon du magma',
    location: 'Plateau Altus',
    inDlc: false,
    done: false,
  },
  {
    name: 'Gilika reine semi-humaine',
    location: 'Mont Gelmir',
    inDlc: false,
    done: false,
  },
  {
    name: 'Nocher Diaphane',
    location: 'Mont Gelmir',
    inDlc: false,
    done: false,
  },
  {
    name: 'Lansseax le dragon ancien',
    location: 'Mont Gelmir',
    inDlc: false,
    done: false,
  },
  {
    name: 'Assassin des couteaux noirs',
    location: 'Mont Gelmir',
    inDlc: false,
    done: false,
  },
  {
    name: 'Garryth le Nécromancien',
    location: 'Mont Gelmir',
    inDlc: false,
    done: false,
  },
  {
    name: 'Tueur de Réprouvés',
    location: 'Mont Gelmir',
    inDlc: false,
    done: false,
  },
  {
    name: 'Parfumeuse Tricia et Chimère léonine',
    location: 'Mont Gelmir',
    inDlc: false,
    done: false,
  },
  {
    name: 'Troll fouisseur',
    location: 'Mont Gelmir',
    inDlc: false,
    done: false,
  },
  {
    name: "Chien de garde de l'arbre des défunts",
    location: 'Mont Gelmir',
    inDlc: false,
    done: false,
  },
  {
    name: 'Loup rouge du Champion',
    location: 'Mont Gelmir',
    inDlc: false,
    done: false,
  },
  {
    name: 'Maggie reine semi-humaine',
    location: 'Mont Gelmir',
    inDlc: false,
    done: false,
  },
  {
    name: 'Elemer du roncier',
    location: 'Mont Gelmir',
    inDlc: false,
    done: false,
  },
  {
    name: 'Maleigh Marais',
    location: 'Mont Gelmir',
    inDlc: false,
    done: false,
  },
  {
    name: 'Margot reine semi-humaine',
    location: 'Mont Gelmir',
    inDlc: false,
    done: false,
  },
  {
    name: "Esprit d'arbre ulcéreux",
    location: 'Mont Gelmir',
    inDlc: false,
    done: false,
  },
  {
    name: 'Adeptes de la Putréfaction',
    location: 'Mont Gelmir',
    inDlc: false,
    done: false,
  },
  {
    name: 'Créature stellaire adulte',
    location: 'Mont Gelmir',
    inDlc: false,
    done: false,
  },
  {
    name: 'Prélat',
    location: 'Mont Gelmir',
    inDlc: false,
    done: false,
  },
  {
    name: 'Dragon du magma',
    location: 'Mont Gelmir',
    inDlc: false,
    done: false,
  },
  {
    name: 'Noble Sanctechair',
    location: 'Mont Gelmir',
    inDlc: false,
    done: false,
  },
  {
    name: 'Les vierges ravisseuses',
    location: 'Mont Gelmir',
    inDlc: false,
    done: false,
  },
  {
    name: 'Rykard seigneur du blasphème',
    location: 'Mont Gelmir',
    inDlc: false,
    done: false,
  },
  {
    name: "Seigneur d'Onyx",
    location: 'Liurnia',
    inDlc: false,
    done: false,
  },
  {
    name: 'Loretta chevaleresse royale',
    location: 'Liurnia',
    inDlc: false,
    done: false,
  },
  {
    name: "Adula dragon de pierre d'éclat",
    location: 'Liurnia',
    inDlc: false,
    done: false,
  },
  {
    name: 'Spectre royal',
    location: 'Liurnia',
    inDlc: false,
    done: false,
  },
  {
    name: 'Cavalier Crépusculaire (Night)',
    location: 'Liurnia',
    inDlc: false,
    done: false,
  },
  {
    name: 'Crystalian',
    location: 'Liurnia',
    inDlc: false,
    done: false,
  },
  {
    name: "Avatar de l'Arbre-Monde",
    location: 'Liurnia',
    inDlc: false,
    done: false,
  },
  {
    name: 'Assassin des couteaux noirs',
    location: 'Liurnia',
    inDlc: false,
    done: false,
  },
  {
    name: 'Ombre du cimetière',
    location: 'Liurnia',
    inDlc: false,
    done: false,
  },
  {
    name: 'Volatile funéraire (Night)',
    location: 'Liurnia',
    inDlc: false,
    done: false,
  },
  {
    name: 'Loup cramoisi de Radagon',
    location: 'Liurnia',
    inDlc: false,
    done: false,
  },
  {
    name: 'Rennala reine de la pleine lune',
    location: 'Liurnia',
    inDlc: false,
    done: false,
  },
  {
    name: 'Crystalians',
    location: 'Liurnia',
    inDlc: false,
    done: false,
  },
  {
    name: "Smarag Dragon de Pierre d'Eclat",
    location: 'Liurnia',
    inDlc: false,
    done: false,
  },
  {
    name: 'Bols Chevalier de Caria',
    location: 'Liurnia',
    inDlc: false,
    done: false,
  },
  {
    name: 'Escargot mande-spectre',
    location: 'Liurnia',
    inDlc: false,
    done: false,
  },
  {
    name: "Avatar de l'Arbre-Monde",
    location: 'Liurnia',
    inDlc: false,
    done: false,
  },
  {
    name: 'Alecto Meneuse des Couteaux Noirs',
    location: 'Liurnia',
    inDlc: false,
    done: false,
  },
  {
    name: "Adula Dragon de Pierre d'Eclat (2nd Position)",
    location: 'Liurnia',
    inDlc: false,
    done: false,
  },
  {
    name: 'Tueur de Réprouvés',
    location: 'Liurnia',
    inDlc: false,
    done: false,
  },
  {
    name: 'Volatile funéraire (Night)',
    location: 'Liurnia',
    inDlc: false,
    done: false,
  },
  {
    name: 'Cavalier Crépusculaire (Night)',
    location: 'Liurnia',
    inDlc: false,
    done: false,
  },
  {
    name: 'Nocher Diaphane',
    location: 'Liurnia',
    inDlc: false,
    done: false,
  },
  {
    name: 'Noble Sanctechair',
    location: 'Liurnia',
    inDlc: false,
    done: false,
  },
  {
    name: "Chien de garde de l'arbre des défunts",
    location: 'Liurnia',
    inDlc: false,
    done: false,
  },
  {
    name: 'Adan voleur du Feu',
    location: 'Liurnia',
    inDlc: false,
    done: false,
  },
  {
    name: 'Chevalier-limier',
    location: 'Liurnia',
    inDlc: false,
    done: false,
  },
  {
    name: 'Chevalier Noble de la Putréfaction',
    location: 'Liurnia',
    inDlc: false,
    done: false,
  },
  {
    name: 'Rejeton greffé',
    location: 'Liurnia',
    inDlc: false,
    done: false,
  },
  {
    name: 'Chimère léonine',
    location: 'Nécrolimbe (Sud)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Volatile funéraire (Night)',
    location: 'Nécrolimbe (Sud)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Cavalier Crépusculaire (Night)',
    location: 'Nécrolimbe (Sud)',
    inDlc: false,
    done: false,
  },
  {
    name: "Chien de garde de l'arbre des défunts",
    location: 'Nécrolimbe (Sud)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Ours Runique',
    location: 'Nécrolimbe (Sud)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Chimère Ecailleuse',
    location: 'Nécrolimbe (Sud)',
    inDlc: false,
    done: false,
  },
  {
    name: "Avatar de l'Arbre-Monde",
    location: 'Nécrolimbe (Sud)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Ancien héros de Zamor',
    location: 'Nécrolimbe (Sud)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Miranda la fleur galeuse',
    location: 'Nécrolimbe (Sud)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Ombre du cimetière',
    location: 'Nécrolimbe (Sud)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Godrick le greffé',
    location: 'Nécrolimbe (Nord)',
    inDlc: false,
    done: false,
  },
  {
    name: "Esprit d'arbre ulcéreux",
    location: 'Nécrolimbe (Nord)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Margit le déchu',
    location: 'Nécrolimbe (Nord)',
    inDlc: false,
    done: false,
  },
  {
    name: "Chien de garde de l'arbre des défunts",
    location: 'Nécrolimbe (Nord)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Chevalier du Creuset',
    location: 'Nécrolimbe (Nord)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Homme-bête de Farum Azula',
    location: 'Nécrolimbe (Nord)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Assassin des couteaux noirs',
    location: 'Nécrolimbe (Nord)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Volatile funéraire (Night)',
    location: 'Nécrolimbe (Nord)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Golem Gardien',
    location: 'Nécrolimbe (Nord)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Duelliste Gardien du Tombeau',
    location: 'Nécrolimbe (Nord)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Troll fouisseur',
    location: 'Nécrolimbe (Nord)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Cavalier Crépusculaire (Night)',
    location: 'Nécrolimbe (Nord)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Agheel le dragon volant',
    location: 'Nécrolimbe (Nord)',
    inDlc: false,
    done: false,
  },
  {
    name: "Esprit d'arbre ulcéreux",
    location: 'Nécrolimbe (Nord)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Sentinelle de l’Arbre',
    location: 'Nécrolimbe (Nord)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Chefs semi-humains',
    location: 'Nécrolimbe (Nord)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Soldat de Godrick',
    location: 'Nécrolimbe (Nord)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Darriwil Chevalier-limier',
    location: 'Nécrolimbe (Nord)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Tête de Citrouille',
    location: 'Nécrolimbe (Nord)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Nocher Diaphane',
    location: 'Nécrolimbe (Nord)',
    inDlc: false,
    done: false,
  },
  {
    name: "Pat l'Affranchi",
    location: 'Nécrolimbe (Nord)',
    inDlc: false,
    done: false,
  },
  {
    name: 'Dragon du magma',
    location: 'Caelid',
    inDlc: false,
    done: false,
  },
  {
    name: 'Avatar Putride',
    location: 'Caelid',
    inDlc: false,
    done: false,
  },
  {
    name: "Chiens de gardes de l'arbre des défunts",
    location: 'Caelid',
    inDlc: false,
    done: false,
  },
  {
    name: 'Tête de Citrouille démente',
    location: 'Caelid',
    inDlc: false,
    done: false,
  },
  {
    name: 'Duelliste Frénétique',
    location: 'Caelid',
    inDlc: false,
    done: false,
  },
  {
    name: 'Ekzykes le putréfié',
    location: 'Caelid',
    inDlc: false,
    done: false,
  },
  {
    name: 'Ombre du cimetière',
    location: 'Caelid',
    inDlc: false,
    done: false,
  },
  {
    name: 'Cavalier Crépusculaire (Night)',
    location: 'Caelid',
    inDlc: false,
    done: false,
  },
  {
    name: 'Volatile funéraire (Night)',
    location: 'Caelid',
    inDlc: false,
    done: false,
  },
  {
    name: "Commandant O'Neil",
    location: 'Caelid',
    inDlc: false,
    done: false,
  },
  {
    name: 'Mage de Bataille Hugues',
    location: 'Caelid',
    inDlc: false,
    done: false,
  },
  {
    name: 'Chevaliers de la Noble Putréfaction',
    location: 'Caelid',
    inDlc: false,
    done: false,
  },
  {
    name: 'Créature stellaire',
    location: 'Caelid',
    inDlc: false,
    done: false,
  },
  {
    name: 'Duo Nox',
    location: 'Caelid',
    inDlc: false,
    done: false,
  },
  {
    name: 'Apôtre Sanctechair',
    location: 'Caelid',
    inDlc: false,
    done: false,
  },
  {
    name: 'Chimère et Chevalier du Creuset',
    location: 'Caelid',
    inDlc: false,
    done: false,
  },
  {
    name: 'Radahn le Fléau des astres',
    location: 'Caelid',
    inDlc: false,
    done: false,
  },
  {
    name: 'Greyroll matriarche des dragons',
    location: 'Caelid',
    inDlc: false,
    done: false,
  },
  {
    name: 'Crystalians',
    location: 'Caelid',
    inDlc: false,
    done: false,
  },
  {
    name: 'Avatar Putride',
    location: 'Caelid',
    inDlc: false,
    done: false,
  },
  {
    name: 'Homme-bête de Farum Azula',
    location: 'Caelid',
    inDlc: false,
    done: false,
  },
  {
    name: 'Esprit d’arbre putride',
    location: 'Caelid',
    inDlc: false,
    done: false,
  },
  {
    name: 'Cavalier Crépusculaire (Night)',
    location: 'Caelid',
    inDlc: false,
    done: false,
  },
  {
    name: 'Greyll le Dragon Volant',
    location: 'Caelid',
    inDlc: false,
    done: false,
  },
  {
    name: 'Gargouille vaillante',
    location: 'Caelid',
    inDlc: false,
    done: false,
  },
];
