export const bosses = [
  {
    name: 'Margit le déchu',
    location: 'Nécrolimbe',
    major: true,
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/margit-3-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Margit,+The+Fell+Omen',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=163938',
  },
  {
    name: 'Godrick le greffé',
    location: 'Nécrolimbe',
    major: true,
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/godrick_the_grafted_bosses_elden_ring_wiki_600px.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Godrick+the+Grafted',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164421',
  },
  {
    name: "Esprit d'arbre ulcéreux",
    location: 'Nécrolimbe',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/ulcerated_tree_spirit.png',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Ulcerated+Tree+Spirit',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165164',
  },
  {
    name: "Chien de garde de l'arbre des défunts",
    location: 'Nécrolimbe',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/burial_watchdog_bosses_elden_ring_wiki_600px.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Erdtree+Burial+Watchdog',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164467',
  },
  {
    name: 'Chevalier du Creuset',
    location: 'Nécrolimbe',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/crucible-knight-stormhill-1.png',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Crucible+Knight',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164476',
  },
  {
    name: 'Homme-bête de Farum Azula',
    location: 'Nécrolimbe',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/beastman-of-farum-azula-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Beastman+of+Farum+Azula',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164472',
  },
  {
    name: 'Assassin des couteaux noirs',
    location: 'Nécrolimbe',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/black-knife-assassin-limgrave-2.png',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Black+Knife+Assassin',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164530',
  },
  {
    name: 'Volatile funéraire (Night)',
    location: 'Nécrolimbe',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/death-bird-limgrave.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Deathbird',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165457',
  },
  {
    name: 'Golem Gardien',
    location: 'Nécrolimbe',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/guardian-golem-field-boss-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Guardian+Golem',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164509',
  },
  {
    name: 'Duelliste Gardien du Tombeau',
    location: 'Nécrolimbe',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/grave-warden-duelist-3.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Grave+Warden+Duelist',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164499',
  },
  {
    name: 'Troll fouisseur',
    location: 'Nécrolimbe',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/stonedigger_troll_bosses_elden_ring_wiki_600px.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Stonedigger+Troll',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164478',
  },
  {
    name: 'Cavalier Crépusculaire (Night)',
    location: 'Nécrolimbe',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/nights-cavalry-limgrave.jpg',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Night's+Cavalry",
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164488',
  },
  {
    name: 'Agheel le dragon volant',
    location: 'Nécrolimbe',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/flying_dragon_agheel_2_bosses_elden_ring_wiki_600px.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Flying+Dragon+Agheel',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164484',
  },
  {
    name: "Esprit d'arbre ulcéreux",
    location: 'Nécrolimbe',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/ulcerated_tree_spirit.png',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Ulcerated+Tree+Spirit',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164143',
  },
  {
    name: 'Sentinelle de l’Arbre',
    location: 'Nécrolimbe',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/tree-sentinel-3.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Tree+Sentinel',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164444',
  },
  {
    name: '2x Chef semi-humains',
    location: 'Nécrolimbe',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/demihuman-chief-boss-enemy-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Demi-Human+Chief',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164457',
  },
  {
    name: 'Soldat de Godrick',
    location: 'Nécrolimbe',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/soldier-of-godrick-boss-elden-rings.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Soldier+of+Godrick',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164420',
  },
  {
    name: 'Darriwil Chevalier-limier',
    location: 'Nécrolimbe',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/bloodhound-knight-darriwil-boss-enemy-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Bloodhound+Knight+Darriwil',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164486',
  },
  {
    name: 'Tête de Citrouille',
    location: 'Nécrolimbe',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/mad-pumpkin-head.png',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Mad+Pumpkin+Head',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164490',
  },
  {
    name: 'Nocher Diaphane',
    location: 'Nécrolimbe',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/tibia-mariner-limgrave-small.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Tibia+Mariner',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164859',
  },
  {
    name: "Pat l'Affranchi",
    location: 'Nécrolimbe',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/patches-npc-photo-elden-ring-wiki-guide-300px-min.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Patches',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164504',
  },
  {
    name: 'Chimère léonine',
    location: 'Péninsule Larmoyante',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/leonine_misbegotten_bosses_elden_ring_wiki_600px.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Leonine+Misbegotten',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164812',
  },
  {
    name: 'Volatile funéraire (Night)',
    location: 'Péninsule Larmoyante',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/death-bird-weeping-peninsula.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Deathbird',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166054',
  },
  {
    name: 'Cavalier Crépusculaire (Night)',
    location: 'Péninsule Larmoyante',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/nights-cavalry-weeping-elden-ring-wiki.jpg',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Night's+Cavalry",
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164659',
  },
  {
    name: "Chien de garde de l'arbre des défunts",
    location: 'Péninsule Larmoyante',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/burial_watchdog_bosses_elden_ring_wiki_600px.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Erdtree+Burial+Watchdog',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165949',
  },
  {
    name: 'Ours Runique',
    location: 'Péninsule Larmoyante',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/runebear_bosses_elden_ring_wiki_guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Runebear',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165462',
  },
  {
    name: 'Chimère Ecailleuse',
    location: 'Péninsule Larmoyante',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/scaly_misbegotten.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Scaly+Misbegotten',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165453',
  },
  {
    name: "Avatar de l'Arbre-Monde",
    location: 'Péninsule Larmoyante',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/erdtree-avatar-weeping-peninsula-elden-rink-wiki-guide-2.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Erdtree+Avatar',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165321',
  },
  {
    name: 'Ancien héros de Zamor',
    location: 'Péninsule Larmoyante',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/ancient-hero-of-zamor-weeping-evergaol-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Ancient+Hero+of+Zamor',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165411',
  },
  {
    name: 'Miranda la fleur galeuse',
    location: 'Péninsule Larmoyante',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/miranda-the-blighted-bloom-field-boss-elden-ring-wiki-guide-300px.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Miranda+the+Blighted+Bloom',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165743',
  },
  {
    name: 'Ombre du cimetière',
    location: 'Péninsule Larmoyante',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/cemetery_shade_bosses_elden_ring_wiki_600px.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Cemetery+Shade',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165317',
  },
  {
    name: '2x Gargouille vaillante',
    location: 'La Siofra',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/gargoyle-2-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Valiant+Gargoyle',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168404',
  },
  {
    name: 'Soldat draconique',
    location: 'La Siofra',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/dragonkin-soldier-boss-enemies-elden-ring-wiki-guide-300px.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Dragonkin+Soldier',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167928',
  },
  {
    name: 'Esprit ancestral',
    location: 'La Siofra',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/ancestor_spirit1-min.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Ancestor+Spirit',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167775',
  },
  {
    name: 'Esprit ancestral royal',
    location: 'La Siofra',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/regal-ancestor-spirit_map-bosses-enemies-elden-ring-wiki-guide-300px.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Regal+Ancestor+Spirit',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167929',
  },
  {
    name: 'Larme imitatrice',
    location: 'La Siofra',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/mimic-tear-boss-enemies-elden-ring-wiki-guide-300px.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Mimic+Tear',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168280',
  },
  {
    name: 'Loup cramoisi de Radagon',
    location: 'Liurnia',
    major: true,
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/red_wolf_of_radagon_1_bosses_elden_ring_wiki_600px.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Red+Wolf+of+Radagon',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165697',
  },
  {
    name: 'Rennala reine de la pleine lune',
    location: 'Liurnia',
    major: true,
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/rennala_queen_of_the_full_moon_bosses_elden_ring_wiki_600px.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Rennala+Queen+of+the+Full+Moon',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164430',
  },
  {
    name: 'Loretta chevaleresse royale',
    location: 'Liurnia',
    major: true,
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/royal_knight_loretta_bosses_elden_ring_wiki_guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Royal+Knight+Loretta',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165490',
  },
  {
    name: "Seigneur d'Onyx",
    location: 'Liurnia',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/onyx-lord-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Onyx+Lord',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166766',
  },
  {
    name: "Adula dragon de pierre d'éclat",
    location: 'Liurnia',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/glintstone-dragon-adula-2-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Glintstone+Dragon+Adula',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167408',
  },
  {
    name: 'Spectre royal',
    location: 'Liurnia',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/royal-revenant-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Royal+Revenant',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166772',
  },
  {
    name: 'Cavalier Crépusculaire (Night)',
    location: 'Liurnia',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/nights-cavalry-2-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Night's+Cavalry",
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166645',
  },
  {
    name: 'Crystalian',
    location: 'Liurnia',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/crystallian-4-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Crystalians',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166381',
  },
  {
    name: "Avatar de l'Arbre-Monde",
    location: 'Liurnia',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/erdtree-avatar-3-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Erdtree+Avatar',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165595',
  },
  {
    name: 'Assassin des couteaux noirs',
    location: 'Liurnia',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/black-knife-assassin-black-knife-catacombs-elden-ring-wiki.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Black+Knife+Assassin',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166482',
  },
  {
    name: 'Ombre du cimetière',
    location: 'Liurnia',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/cemetary-shade-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Cemetery+Shade',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166484',
  },
  {
    name: 'Volatile funéraire des cimes (Night)',
    location: 'Liurnia',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/death-rite-bird-3-hq-elden-ring-wiki-guide.jpg?v=1664766957687',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Death+Rite+Bird',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166501',
  },
  {
    name: '2x Crystalian',
    location: 'Liurnia',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/crystallian-6-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Crystalians',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166455',
  },
  {
    name: "Smarag Dragon de Pierre d'Eclat",
    location: 'Liurnia',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/glintstone-dragon-smarag-2-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Glintstone+Dragon+Smarag',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165267',
  },
  {
    name: 'Bols Chevalier de Caria',
    location: 'Liurnia',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/bols-carian-knight-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Bols+Carian+Knight',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167325',
  },
  {
    name: 'Escargot mande-spectre',
    location: 'Liurnia',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/spirit-caller-snail-2-hq-enemy-elden-ring-wiki.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Spirit-Caller+Snail',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166749',
  },
  {
    name: "Avatar de l'Arbre-Monde",
    location: 'Liurnia',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/erdtree-avatar-2-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Erdtree+Avatar',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165594',
  },
  {
    name: 'Alecto Meneuse des Couteaux Noirs',
    location: 'Liurnia',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/alecto-black-knife-ringleader-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Alecto,+Black+Knife+Ringleader',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=171212',
  },
  {
    name: "Adula Dragon de Pierre d'Eclat (2nd Position)",
    location: 'Liurnia',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/glintstone_dragon_bosses_elden_ring_wiki_600px.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Glintstone+Dragon+Adula',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167576',
  },
  {
    name: 'Tueur de Réprouvés',
    location: 'Liurnia',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/omenkiller-3-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Omenkiller',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166426',
  },
  {
    name: 'Volatile funéraire (Night)',
    location: 'Liurnia',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/deathbird-2-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Deathbird',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165597',
  },
  {
    name: 'Cavalier Crépusculaire (Night)',
    location: 'Liurnia',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/nights-cavalry-2-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Night's+Cavalry",
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166181',
  },
  {
    name: 'Nocher Diaphane',
    location: 'Liurnia',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/tibia-mariner-liurnia.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Tibia+Mariner',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166619',
  },
  {
    name: 'Noble Sanctechair',
    location: 'Liurnia',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/godskin-noble-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Godskin+Noble',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168277',
  },
  {
    name: "Chien de garde de l'arbre des défunts",
    location: 'Liurnia',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/erdtree-burial-watchdog-2-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Erdtree+Burial+Watchdog',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168517',
  },
  {
    name: 'Adan voleur du Feu',
    location: 'Liurnia',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/adan-thief-of-fire-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Adan,+Thief+of+Fire',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166505',
  },
  {
    name: 'Chevalier-limier',
    location: 'Liurnia',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/bloodhunt-knight-2-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Bloodhound+Knight',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168523',
  },
  {
    name: 'Chevalier Noble de la Putréfaction',
    location: 'Liurnia',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/cleanrot-knight-6-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Cleanrot+Knight',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166386',
  },
  {
    name: 'Rejeton greffé',
    location: 'Liurnia',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/er_grafted_scion.png',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Grafted+Scion',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164433',
  },
  {
    name: 'Astel le Rejeton du vide',
    location: "L'Ainsel",
    major: true,
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/astel-naturalborn-of-the-void-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Astel+Naturalborn+of+the+Void',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167488',
  },
  {
    name: 'Soldat draconide de Nokstella',
    location: "L'Ainsel",
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/dragonkin-soldier-nokstella-2-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Dragonkin+Soldier+of+Nokstella',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167625',
  },
  {
    name: 'Soldat draconide',
    location: "L'Ainsel",
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/dragonkin_soldier_bosses_elden_ring_wiki_600px.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Dragonkin+Soldier',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168515',
  },
  {
    name: 'Radahn le Fléau des astres',
    location: 'Caelid',
    major: true,
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/radahn-2-hq-enemy-elden-ring-wiki.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Starscourge+Radahn',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165444',
  },
  {
    name: 'Dragon du magma',
    location: 'Caelid',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/magma_wyrm_bosses_elden_ring_wiki_guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Magma+Wyrm',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167222',
  },
  {
    name: 'Avatar Putride',
    location: 'Caelid',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/putrid-avatar-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Putrid+Avatar',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166512',
  },
  {
    name: "2x Chien de garde de l'arbre des défunts",
    location: 'Caelid',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/burial_watchdog_bosses_elden_ring_wiki_600px.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Erdtree+Burial+Watchdog',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166671',
  },
  {
    name: 'Tête de Citrouille démente',
    location: 'Caelid',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/boss-mad-pumpkin-heads-01-elden-ring-wiki-600px.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Mad+Pumpkin+Head',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166738',
  },
  {
    name: 'Duelliste Frénétique',
    location: 'Caelid',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/frenzied-duelist-axe-elden-ring-wiki-guide-300px.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Frenzied+Duelist',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168033',
  },
  {
    name: 'Ekzykes le putréfié',
    location: 'Caelid',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/decaying_ekzykes_bosses_elden_ring_wiki_guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Decaying+Ekzykes',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165933',
  },
  {
    name: 'Ombre du cimetière',
    location: 'Caelid',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/cemetery_shade_bosses_elden_ring_wiki_600px.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Cemetery+Shade',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168518',
  },
  {
    name: 'Cavalier Crépusculaire (Night)',
    location: 'Caelid',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/nights-cavalry-6-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Night's+Cavalry",
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166477',
  },
  {
    name: 'Volatile funéraire des cimes (Night)',
    location: 'Caelid',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/death-rite-bird-4-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Death+Rite+Bird',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167019',
  },
  {
    name: "Commandant O'Neil",
    location: 'Caelid',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/commander-o-neil-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Commander+O'Neil",
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166073',
  },
  {
    name: 'Mage de Bataille Hugues',
    location: 'Caelid',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/battlemage-hugues-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Battlemage+Hugues',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167402',
  },
  {
    name: '2x Chevalier de la Noble Putréfaction',
    location: 'Caelid',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/cleanrot-knight-5-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Cleanrot+Knight',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168213',
  },
  {
    name: 'Créature stellaire',
    location: 'Caelid',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/fallingstar-beast-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Fallingstar+Beast',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167582',
  },
  {
    name: '2x Nox',
    location: 'Caelid',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/nox-swordstress-nox-monk_-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Nox+Swordstress+&+Nox+Priest',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166499',
  },
  {
    name: 'Apôtre Sanctechair',
    location: 'Caelid',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/godskin-apostle-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Godskin+Apostle',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166668',
  },
  {
    name: 'Chimère et Chevalier du Creuset',
    location: 'Caelid',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/crucible-knight-and-misbegotten-warrior-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Crucible+Knight+and+Misbegotten+Warrior',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166176',
  },
  {
    name: 'Greyoll matriarche des dragons',
    location: 'Caelid',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/greyoll_bosses_elden_ring_wiki_guide_300px.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Elder+Dragon+Greyoll',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166189',
  },
  {
    name: '3x Crystalian',
    location: 'Caelid',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/putrid-crystallian-7-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Putrid+Crystalians',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167921',
  },
  {
    name: 'Avatar Putride',
    location: 'Caelid',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/putrid-avatar-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Putrid+Avatar',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166615',
  },
  {
    name: 'Homme-bête de Farum Azula',
    location: 'Caelid',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/beastmen-duo-1.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Beastman+of+Farum+Azula',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167916',
  },
  {
    name: 'Esprit d’arbre putride',
    location: 'Caelid',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/putrid-tree-spirit-boss-elden-ring-wiki-guide-300px-min.jpeg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Putrid+Tree+Spirit',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167378',
  },
  {
    name: 'Cavalier Crépusculaire (Night)',
    location: 'Caelid',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/nights-cavalry-dragonbarrow-elden-ring-wiki.jpg',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Night's+Cavalry",
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166616',
  },
  {
    name: 'Greyll le Dragon Volant',
    location: 'Caelid',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/flying_dragon_greyll_bosses_elden_ring_wiki_guide_300px.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Flying+Dragon+Greyll',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166013',
  },
  {
    name: 'Gargouille vaillante',
    location: 'Caelid',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/black-blade-kindred-1-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Black+Blade+Kindred',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166006',
  },
  {
    name: 'Makar le Dragon du magma',
    location: 'Plateau Altus',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/magma-wyrm-3-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Magma+Wyrm+Makar',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166245',
  },
  {
    name: 'Godefroy le greffé',
    location: 'Plateau Altus',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/godefroy-the-grafted-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Godefroy+the+Grafted',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167645',
  },
  {
    name: 'Cavalier Crépusculaire (Night)',
    location: 'Plateau Altus',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/nights-cavalry-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Night's+Cavalry",
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167893',
  },
  {
    name: 'Créature stellaire',
    location: 'Plateau Altus',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/fallingstar_beast_altus_plateau_enemies_elden_ring_wiki_300px.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Fallingstar+Beast',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167585',
  },
  {
    name: '2x Sentinelle de l’Arbre',
    location: 'Plateau Altus',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/tree-sentinel-duo-2-small.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Tree+Sentinel',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167584',
  },
  {
    name: 'Miranda et le Tueur de Réprouvés',
    location: 'Plateau Altus',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/miranda-and-omenkiller.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Omenkiller+and+Miranda,+the+Blighted+Bloom',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=169017',
  },
  {
    name: 'Lansseax le dragon ancien',
    location: 'Plateau Altus',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/ancient-dragon-lansseax-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Ancient+Dragon+Lansseax',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168510',
  },
  {
    name: 'Ancien héros de Zamor',
    location: 'Plateau Altus',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/ancient-hero-of-zamor-2-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Ancient+Hero+of+Zamor',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=175115',
  },
  {
    name: 'Assassin des couteaux noirs',
    location: 'Plateau Altus',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/black-knife-assassin-sainted-heros-elden-ring-wiki.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Black+Knife+Assassin',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167676',
  },
  {
    name: '2x Crystalian',
    location: 'Plateau Altus',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/crystallian-5-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Crystalians',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168080',
  },
  {
    name: 'Face de Ver',
    location: 'Plateau Altus',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/wormface-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Wormface',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167317',
  },
  {
    name: 'Apôtre Sanctechair',
    location: 'Plateau Altus',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/godskin-apostle-3-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Godskin+Apostle',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166231',
  },
  {
    name: 'Noble Sanglant',
    location: 'Plateau Altus',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/sanguine-noble-6-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Sanguine+Noble',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167656',
  },
  {
    name: 'Rykard seigneur du blasphème',
    location: 'Mont Gelmir',
    major: true,
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/god-devouring-serpent-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Rykard,+Lord+of+Blasphemy',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167571',
  },
  {
    name: 'Gilika reine semi-humaine',
    location: 'Mont Gelmir',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/queen-gilika-elden-ring-wiki.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Demi-Human+Queen+Gilika',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167566',
  },
  {
    name: 'Nocher Diaphane',
    location: 'Mont Gelmir',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/tibia-manner-enemy-3-hq-big-elden-ring-wiki.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Tibia+Mariner',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167560',
  },
  {
    name: 'Lansseax le dragon ancien',
    location: 'Mont Gelmir',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/ancient-dragon-lansseax-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Ancient+Dragon+Lansseax',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167545',
  },
  {
    name: 'Assassin des couteaux noirs',
    location: 'Mont Gelmir',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/black-knife-assassin-sages-cave-elden-ring-wiki.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Black+Knife+Assassin',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166678',
  },
  {
    name: 'Garryth le Nécromancien',
    location: 'Mont Gelmir',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/necromancer-garris-elden-ring-wiki.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Necromancer+Garris',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166675',
  },
  {
    name: 'Tueur de Réprouvés',
    location: 'Mont Gelmir',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/omenkiller-3-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Omenkiller',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168973',
  },
  {
    name: 'Parfumeuse Tricia et Chimère léonine',
    location: 'Mont Gelmir',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/perfumer-tricia-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Perfumer+Tricia',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167394',
  },
  {
    name: 'Troll fouisseur',
    location: 'Mont Gelmir',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/stonedigger-troll-2-hq-enemy-elden-ring-wiki.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Stonedigger+Troll',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168507',
  },
  {
    name: "Chien de garde de l'arbre des défunts",
    location: 'Mont Gelmir',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/erdtree-burial-watchdog-3-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Erdtree+Burial+Watchdog',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168513',
  },
  {
    name: 'Loup cramoisi du Champion',
    location: 'Mont Gelmir',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/red-wolf-of-radagon-3-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Red+Wolf+of+the+Champion',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168140',
  },
  {
    name: 'Maggie reine semi-humaine',
    location: 'Mont Gelmir',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/demi-human-queen-maggie-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Demi-Human+Queen+Maggie',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167815',
  },
  {
    name: 'Elemer du roncier',
    location: 'Mont Gelmir',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/elemer-of-the-briar-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Elemer+of+the+Briar',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167323',
  },
  {
    name: 'Maleigh Marais',
    location: 'Mont Gelmir',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/maleigh_marais_npc_inavder_elden_ring_wiki_guide_300px.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Maleigh+Marais,+Shaded+Castle+Castellan',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166754',
  },
  {
    name: 'Margot reine semi-humaine',
    location: 'Mont Gelmir',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/demi-human-queen-margot-2-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Demi-Human+Queen+Margot',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167366',
  },
  {
    name: "Esprit d'arbre ulcéreux",
    location: 'Mont Gelmir',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/uncerated-tree-spirit-5-hq-elden-ring-wiki.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Ulcerated+Tree+Spirit',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167812',
  },
  {
    name: '2x Adepte de la Putréfaction',
    location: 'Mont Gelmir',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/kindred-of-rot-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Kindred+of+Rot',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168512',
  },
  {
    name: 'Créature stellaire adulte',
    location: 'Mont Gelmir',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/full-grown-fallingstar-beast-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Full-Grown+Fallingstar+Beast',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167365',
  },
  {
    name: 'Prélat',
    location: 'Mont Gelmir',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/fire-prelate-2-hs-enemy-elden-ring-wiki.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Fire+Prelate',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=169063',
  },
  {
    name: 'Dragon du magma',
    location: 'Mont Gelmir',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/magma-wyrm-2-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Magma+Wyrm',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167377',
  },
  {
    name: 'Noble Sanctechair',
    location: 'Mont Gelmir',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/godskin-noble-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Godskin+Noble',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168177',
  },
  {
    name: '2x Vierge Ravisseuse',
    location: 'Mont Gelmir',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/abductor-virgins-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Abductor+Virgins',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168514',
  },
  {
    name: 'Mohg le réprouvé',
    location: 'Leyndell, Capitale Royale',
    major: true,
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/mogh_the_omen.png',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Mohg,+the+Omen',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168657',
  },
  {
    name: "Godfrey premier Seigneur d'Elden (Gold)",
    location: 'Leyndell, Capitale Royale',
    major: true,
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/godfrey-first-elden-lord-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Godfrey,+First+Elden+Lord+(Golden+Shade)',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167693',
  },
  {
    name: 'Morgott roi des Réprouvés',
    location: 'Leyndell, Capitale Royale',
    major: true,
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/morgott-omen-king-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Morgott+the+Omen+King',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167374',
  },
  {
    name: 'Volatile funéraire (Night)',
    location: 'Leyndell, Capitale Royale',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/deathbird-1-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Deathbird',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167182',
  },
  {
    name: 'Margit le déchu',
    location: 'Leyndell, Capitale Royale',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/margit-altus-2.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Margit,+The+Fell+Omen',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168001',
  },
  {
    name: "Seigneur d'Onyx",
    location: 'Leyndell, Capitale Royale',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/onyx-lord-2-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Onyx+Lord',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168154',
  },
  {
    name: "Esprit d'arbre ulcéreux",
    location: 'Leyndell, Capitale Royale',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/ulcerated-tree-spirit-1.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Ulcerated+Tree+Spirit',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167586',
  },
  {
    name: "Sentinelle draconique de l'Arbre",
    location: 'Leyndell, Capitale Royale',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/draconic-tree-sentinel-2-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Draconic+Tree+Sentinel',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167180',
  },
  {
    name: 'Duelliste Gardien du Tombeau',
    location: 'Leyndell, Capitale Royale',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/grave-warden-duelist-3-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Grave+Warden+Duelist',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167018',
  },
  {
    name: 'Ordovis 2x Chevalier du Creuset',
    location: 'Leyndell, Capitale Royale',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/crucible-knight-and-ordovis-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Crucible+Knight+Ordovis',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167535',
  },
  {
    name: "Esprit d'arbre ulcéreux",
    location: 'Leyndell, Capitale Royale',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/ulcerated_tree_spirit_enemies_elden_ring_wiki_600px.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Ulcerated+Tree+Spirit',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167141',
  },
  {
    name: "Avatar de l'Arbre-Monde",
    location: 'Leyndell, Capitale Royale',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/erdtree-avatar-boss-elden-ring-compressed-300px.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Erdtree+Avatar',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168147',
  },
  {
    name: 'Esgar prêtre de sang',
    location: 'Leyndell, Capitale Royale',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/esgar_priest_of_blood_bosses_elden_ring_wiki_guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Esgar,+Priest+of+Blood',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=175359',
  },
  {
    name: 'Jumeaux Abominables',
    location: 'Leyndell, Capitale Royale',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/fell-twin-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Fell+Twins',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167171',
  },
  {
    name: 'Fortissax la Liche draconique',
    location: 'Profondeurs de Fonderacine',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/lichdragon-fortissax-2-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Lichdragon+Fortissax',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168158',
  },
  {
    name: 'Champions de Fia',
    location: 'Profondeurs de Fonderacine',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/fias-champion-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Fia's+champions",
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168424',
  },
  {
    name: 'Siluria du Creuset',
    location: 'Profondeurs de Fonderacine',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/crucible-knight-siluria-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Crucible+Knight+Siluria',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168281',
  },
  {
    name: "Avatar de l'Arbre-Monde",
    location: 'Profondeurs de Fonderacine',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/erdtree-avatar-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Erdtree+Avatar',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168442',
  },
  {
    name: 'Commandant Niall',
    location: 'Cimes des géants',
    major: true,
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/commander-niall-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Commander+Niall',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167290',
  },
  {
    name: 'Géant de feu',
    location: 'Cimes des géants',
    major: true,
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/fire_giant_eye.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Fire+Giant',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167375',
  },
  {
    name: 'Cavalier Crépusculaire (Night)',
    location: 'Cimes des géants',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/nights-cavalry-forbidden-lands-elden-ring-wiki.jpg',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Night's+Cavalry",
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168519',
  },
  {
    name: 'Gargouille vaillante',
    location: 'Cimes des géants',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/black-blade-kindred-2-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Black+Blade+Kindred',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168016',
  },
  {
    name: 'Ancien héros de Zamor',
    location: 'Cimes des géants',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/ancient_hero_of_zamor_enemies_elden_ring_wiki_300px.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Ancient+Hero+of+Zamor',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167371',
  },
  {
    name: "Esprit d'arbre ulcéreux",
    location: 'Cimes des géants',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/ulcerated_tree_spirit.png',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Ulcerated+Tree+Spirit',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167668',
  },
  {
    name: 'Volatile funéraire des cimes',
    location: 'Cimes des géants',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/death-rite-bird-2-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Death+Rite+Bird',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168010',
  },
  {
    name: 'Nocher Diaphane',
    location: 'Cimes des géants',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/tibia-manner-enemy-big-elden-ring-wiki.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Tibia+Mariner',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=166631',
  },
  {
    name: "Avatar de l'Arbre-Monde",
    location: 'Cimes des géants',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/erdtree-avatar-4-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Erdtree+Avatar',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167138',
  },
  {
    name: 'Gardien en chef Arghanthy',
    location: 'Cimes des géants',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/chief-guardian-arghanthy-1-enemy-elden-ring-wiki.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Chief+Guardian+Arghanthy',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=169140',
  },
  {
    name: 'Vyke chevalier de la Table ronde',
    location: 'Cimes des géants',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/vyke-1-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Roundtable+Knight+Vyke',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168377',
  },
  {
    name: 'Boréalis la Brume Glaciale',
    location: 'Cimes des géants',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/borealis-the-freezing-fog-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Borealis+the+Freezing+Fog',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165642',
  },
  {
    name: 'Escargot Mande-Spectre',
    location: 'Cimes des géants',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/spirit-caller-snail-1-hs-enemy-elden-ring-wiki.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Spirit-Caller+Snail',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=169802',
  },
  {
    name: 'Volatile funéraire des cimes (Night)',
    location: 'Champs de neige consacrés',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/death-rite-bird-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Death+Rite+Bird',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168520',
  },
  {
    name: 'Astel la Constellation des Ténèbres',
    location: 'Champs de neige consacrés',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/astel-naturalborn-of-the-void-3-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Astel,+Stars+of+Darkness',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168224',
  },
  {
    name: '2x Cavalier Crépusculaire',
    location: 'Champs de neige consacrés',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/nights-cavalry-5-elden-ring-wiki-guide.jpg',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Night's+Cavalry",
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168493',
  },
  {
    name: 'Larme imitatrice errante',
    location: 'Champs de neige consacrés',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/stray-mimic-tear-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Mimic+Tear',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=169799',
  },
  {
    name: 'Duelliste Gardien du Tombeau putride',
    location: 'Champs de neige consacrés',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/putrid-grave-warden-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Putrid+Grave+Warden+Duelist',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168389',
  },
  {
    name: 'Avatar Putride',
    location: 'Champs de neige consacrés',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/putrid-avatar-2-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Putrid+Avatar',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168521',
  },
  {
    name: 'Chimère léonine',
    location: 'Champs de neige consacrés',
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/misbegotten-crusader-bloom-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Misbegotten+Crusader',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168661',
  },
  {
    name: 'Theodorix le Grand Ver',
    location: 'Champs de neige consacrés',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/theodorix_6.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Great+Wyrm+Theodorix',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168186',
  },
  {
    name: 'Mohg Seigneur du Sang',
    location: 'Palais Mohgwyn',
    major: true,
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/mohg.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Mohg,+Lord+of+Blood',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168412',
  },
  {
    name: "Loretta Chevaleresse de l'Arbre-Sacré",
    location: 'Arbre-Sacré de Miquella',
    major: true,
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/loretta-knight-of-the-haligtree-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Loretta,+Knight+of+the+Haligtree',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168228',
  },
  {
    name: 'Malenia Épée de Nicolas',
    location: 'Arbre-Sacré de Miquella',
    major: true,
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/malenia,-blade-of-miquella.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Malenia+Blade+of+Miquella',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167678',
  },
  {
    name: 'Placidusax Seigneur Draconique',
    location: 'Farum Azula',
    major: true,
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/dragonlord-placidusax-boss-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Dragonlord+Placidusax',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=168522',
  },
  {
    name: "Maliketh la Lame d'ébène",
    location: 'Farum Azula',
    major: true,
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/maliketh-the-black-blade-4k.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Maliketh,+the+Black+Blade',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167619',
  },
  {
    name: '2x Sanctechair',
    location: 'Farum Azula',
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/godskin-duo-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Godskin+Duo',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167392',
  },
  {
    name: "Sire Gideon Ofnir l'Omniscient",
    location: 'Leyndell, Capitale des Cendres',
    major: true,
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/ofnir-1-hq-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Sir+Gideon+Ofnir,+the+All-Knowing+(Boss)',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=176583',
  },
  {
    name: "Godfrey premier Seigneur d'Elden",
    location: 'Leyndell, Capitale des Cendres',
    major: true,
    imageUrl: 'https://eldenring.wiki.fextralife.com/file/Elden-Ring/godfrey,hoarah.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Godfrey,+First+Elden+Lord',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=176808',
  },
  {
    name: "Radagon de l'Ordre d'or",
    location: 'Leyndell, Capitale des Cendres',
    major: true,
    imageUrl:
      'https://eldenring.wiki.fextralife.com/file/Elden-Ring/radagon-of-the-golden-order-boss-elden-ring-wiki-guide.jpg',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Radagon+of+the+Golden+Order',
    locationUrl: 'https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=176996',
  },
];
