export const talismans = [
  {
    type: 'talisman',
    name: "Médaillon d'ambre pourpre",
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Crimson+Amber+Medallion',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Médaillon d'ambre pourpre +1",
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Crimson+Amber+Medallion',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Médaillon d'ambre pourpre +2",
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Crimson+Amber+Medallion',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Médaillon d'ambre pourpre +3",
    inDlc: true,
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Crimson+Amber+Medallion',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de la graine pourpre',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Crimson+Seed+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de la graine pourpre +1',
    inDlc: true,
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Crimson+Seed+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de la larme bénie',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Blessed+Dew+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Médaillon d'ambre céruléen",
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Cerulean+Amber+Medallion',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Médaillon d'ambre céruléen +1",
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Cerulean+Amber+Medallion',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Médaillon d'ambre céruléen +2",
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Cerulean+Amber+Medallion',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Médaillon d'ambre céruléen +3",
    inDlc: true,
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Cerulean+Amber+Medallion',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de la graine céruléenne',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Cerulean+Seed+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de la graine céruléenne +1',
    inDlc: true,
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Cerulean+Seed+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de la larme bleue bénie',
    inDlc: true,
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Blessed+Blue+Dew+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman du don du seigneur',
    inDlc: true,
    imageUrl: '',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Talisman+of+Lord's+Bestowal",
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Médaillon d'ambre vert émeraude",
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Viridian+Amber+Medallion',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Médaillon d'ambre vert émeraude +1",
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Viridian+Amber+Medallion',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Médaillon d'ambre vert émeraude +2",
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Viridian+Amber+Medallion',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Médaillon d'ambre vert émeraude +3",
    inDlc: true,
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Viridian+Amber+Medallion',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de tortue verte',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Green+Turtle+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de tortue à deux têtes',
    inDlc: true,
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Green+Turtle+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Talisman d'arsenal",
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Arsenal+Charm',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Talisman d'arsenal +1",
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Arsenal+Charm',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Arsenal de la Grande jarre',
    imageUrl: '',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Great-Jar's+Arsenal",
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Faveur de l'Arbre-Monde",
    imageUrl: '',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Erdtree's+Favor",
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Faveur de l'Arbre-Monde +1",
    imageUrl: '',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Erdtree's+Favor",
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Faveur de l'Arbre-Monde +2",
    imageUrl: '',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Erdtree's+Favor",
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Sceau scarifié de Radagon',
    imageUrl: '',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Radagon's+Scarseal",
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Sceau meurtri de Radagon',
    imageUrl: '',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Radagon's+Soreseal",
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Sceau scarifié de Marika',
    imageUrl: '',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Marika's+Scarseal",
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Sceau meurtri de Marika',
    imageUrl: '',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Marika's+Soreseal",
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Héritage du Fléau des astres',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Starscourge+Heirloom',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Héritage de l'épéiste amputée",
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Prosthesis-Wearer+Heirloom',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Héritage de l'astrologue",
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Stargazer+Heirloom',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Héritage des Deux Doigts',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Two+Fingers+Heirloom',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Héritage de la Divinité extérieure',
    inDlc: true,
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Outer+God+Heirloom',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de bouclier draconique',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Dragoncrest+Shield+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de bouclier draconique +1',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Dragoncrest+Shield+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de bouclier draconique +2',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Dragoncrest+Shield+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de pavois draconique',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Dragoncrest+Greatshield+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de dragon magique',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Spelldrake+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de dragon magique +1',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Spelldrake+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de dragon magique +2',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Spelldrake+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de dragon magique +3',
    inDlc: true,
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Spelldrake+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de dragon de feu',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Flamedrake+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de dragon de feu +1',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Flamedrake+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de dragon de feu +2',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Flamedrake+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de dragon de feu +3',
    inDlc: true,
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Flamedrake+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de dragon de foudre',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Boltdrake+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de dragon de foudre +1',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Boltdrake+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de dragon de foudre +2',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Boltdrake+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de dragon de foudre +3',
    inDlc: true,
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Boltdrake+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de dragon sacré',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Haligdrake+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de dragon sacré +1',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Haligdrake+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de dragon sacré +2',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Haligdrake+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Tresse dorée',
    inDlc: true,
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Golden+Braid',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de dragon de perle',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Pearldrake+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de dragon de perle +1',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Pearldrake+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de dragon de perle +2',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Pearldrake+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de dragon de perle +3',
    inDlc: true,
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Pearldrake+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Corne d'immunité",
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Immunizing+Horn+Charm',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Corne d'immunité +1",
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Immunizing+Horn+Charm',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Corne d'immunité +2",
    inDlc: true,
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Immunizing+Horn+Charm',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Corne de robustesse',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Stalwart+Horn+Charm',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Corne de robustesse +1',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Stalwart+Horn+Charm',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Corne de robustesse +2',
    inDlc: true,
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Stalwart+Horn+Charm',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Corne de focalisation',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Clarifying+Horn+Charm',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Corne de focalisation +1',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Clarifying+Horn+Charm',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Corne de focalisation +2',
    inDlc: true,
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Clarifying+Horn+Charm',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Pendentif bariolé',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Mottled+Necklace',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Pendentif bariolé +1',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Mottled+Necklace',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Pendentif bariolé +2',
    inDlc: true,
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Mottled+Necklace',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Excroissance du Prince de la Mort',
    imageUrl: '',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Prince+of+Death's+Pustule",
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Kyste du Prince de la Mort',
    imageUrl: '',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Prince+of+Death's+Cyst",
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Talisman d'altération",
    inDlc: true,
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Ailment+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de la dague',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Dagger+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Talisman d'épée courbée",
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Curved+Sword+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de la lame double',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Twinblade+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de la hache',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Axe+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman du marteau',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Hammer+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de la lance',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Spear+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de la lance de cavalerie',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Lance+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de la griffe',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Claw+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Talisman d'épée à deux mains",
    inDlc: true,
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Two-Handed+Sword+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de pavois',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Greatshield+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman du bouclier perlé',
    inDlc: true,
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Pearl+Shield+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Enchevêtrement de riposte',
    inDlc: true,
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Retaliatory+Crossed-Tree',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Enchevêtrement de lacération',
    inDlc: true,
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Lacerating+Crossed-Tree',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman des flèches mordantes',
    imageUrl: '',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Arrow's+Sting+Talisman",
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman des flèches filantes',
    imageUrl: '',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Arrow's+Reach+Talisman",
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman des flèches mordantes (DLC)',
    inDlc: true,
    imageUrl: '',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Arrow's+Soaring+Sting+Talisman",
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de tir précis',
    inDlc: true,
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Sharpshot+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Talisman de l'amalgame sculpté",
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Graven-School+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Talisman de l'amas sculpté",
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Graven-Mass+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman en toile des fidèles',
    imageUrl: '',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Faithful's+Canvas+Talisman",
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman en toile des ouailles',
    imageUrl: '',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Flock's+Canvas+Talisman",
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Lame de pierre d'éclat primordiale",
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Primal+Glintstone+Blade',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Lune de Nokstella',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Moon+of+Nokstella',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Talisman d'ancien seigneur",
    imageUrl: '',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Old+Lord's+Talisman",
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Icône de Radagon',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Radagon+Icon',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Poussière d'étoiles chérie",
    inDlc: true,
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Beloved+Stardust',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Médaillon de cri',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Roar+Medallion',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Jarre de compagnie',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Companion+Jar',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de Parfumeur',
    imageUrl: '',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Perfumer's+Talisman",
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Emblème de Caria à filigrane',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Carian+Filigreed+Crest',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Fragment de guerrier-jarre',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Warrior+Jar+Shard',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Fragment d'Alexander",
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Shard+of+Alexander',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Icône de Godfrey',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Godfrey+Icon',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Camée de Rellana',
    inDlc: true,
    imageUrl: '',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Rellana's+Cameo",
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de pierre brisée',
    inDlc: true,
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Shattered+Stone+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de forgeron',
    inDlc: true,
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Smithing+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de la bête divine enragée',
    inDlc: true,
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Enraged+Divine+Beast',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Talisman de l'Effroyable",
    inDlc: true,
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Talisman+of+the+Dread',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman du mouflon',
    imageUrl: '',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Bull-Goat's+Talisman",
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de la danseuse bleue',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Blue+Dancer+Charm',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Disque vert-de-gris',
    inDlc: true,
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Verdigris+Discus',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman du scorpion magique',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Magic+Scorpion+Charm',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman du scorpion de feu',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Fire+Scorpion+Charm',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman du scorpion de foudre',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Lightning+Scorpion+Charm',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman du scorpion sacré',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Sacred+Scorpion+Charm',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman à écaille du Creuset',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Crucible+Scale+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman à plume du Creuset',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Crucible+Feather+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman à noeud du Creuset',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Crucible+Knot+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman à plume raffiné du Creuset',
    inDlc: true,
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Fine+Crucible+Feather+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de tous les Creusets',
    inDlc: true,
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Talisman+of+All+Crucibles',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Lame cornue aux plumes rouges',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Red-Feathered+Branchsword',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Lame cornue aux plumes bleues',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Blue-Feathered+Branchsword',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Talisman d'épée rituelle",
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Ritual+Sword+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de bouclier rituel',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Ritual+Shield+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Dague pourpre de l'assassin",
    imageUrl: '',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Assassin's+Crimson+Dagger",
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Dague céruléenne de l'assassin",
    imageUrl: '',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Assassin's+Cerulean+Dagger",
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Insigne d'épée ailée",
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Winged+Sword+Insignia',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Insigne d'épée ailée putréfiée",
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Rotten+Winged+Sword+Insignia',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Prothèse de Milicent',
    imageUrl: '',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Millicent's+Prosthesis",
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Lange sanctechair',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Godskin+Swaddling+Cloth',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Exultation des adptes de la putréfaction',
    imageUrl: '',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Kindred+of+Rot's+Exultation",
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Exultation du seigneur du sang',
    imageUrl: '',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Lord+of+Blood's+Exultation",
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Exultation de l'ancien",
    inDlc: true,
    imageUrl: '',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Aged+One's+Exultation",
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Sourire de sainte Trina',
    inDlc: true,
    imageUrl: '',
    wikiUrl: "https://eldenring.wiki.fextralife.com/St.+Trina's+Smile",
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Lame de miséricorde',
    inDlc: true,
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Blade+of+Mercy',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Camée de pillard',
    imageUrl: '',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Taker's+Cameo",
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Corne de l'esprit ancestral",
    imageUrl: '',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Ancestral+Spirit's+Horn",
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Insigne de croisade',
    inDlc: true,
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Crusade+Insignia',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Bouquet séché',
    inDlc: true,
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Dried+Bouquet',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Scarabée d'or",
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Golden+Scarab',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Scarabée d'argent",
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Silver+Scarab',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Fiole de Crepus',
    imageUrl: '',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Crepus's+Vial",
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Cape dissimulatrice',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Concealing+Veil',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman du chat à longue queue',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Longtail+Cat+Talisman',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Miroir retors de Doigt crochu',
    imageUrl: '',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Furled+Finger's+Trick-Mirror",
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Miroir retors d'hôte",
    imageUrl: '',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Host's+Trick-Mirror",
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Malheur de Shabiri',
    imageUrl: '',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Shabriri's+Woe",
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Malheur de Daedicar',
    imageUrl: '',
    wikiUrl: "https://eldenring.wiki.fextralife.com/Daedicar's+Woe",
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Branche sacrificielle',
    imageUrl: '',
    wikiUrl: 'https://eldenring.wiki.fextralife.com/Sacrificial+Twig',
    locationUrl: '',
  },
];
