export const talismans = [
  {
    type: 'talisman',
    name: "Médaillon d'ambre pourpre",
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Médaillon d'ambre pourpre +1",
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Médaillon d'ambre pourpre +2",
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Médaillon d'ambre pourpre +3",
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de la graine pourpre',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de la graine pourpre +1',
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de la larme bénie',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Médaillon d'ambre céruléen",
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Médaillon d'ambre céruléen +1",
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Médaillon d'ambre céruléen +2",
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Médaillon d'ambre céruléen +3",
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de la graine céruléenne',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de la graine céruléenne +1',
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de la larme bleue bénie',
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman du don du seigneur',
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Médaillon d'ambre vert émeraude",
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Médaillon d'ambre vert émeraude +1",
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Médaillon d'ambre vert émeraude +2",
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Médaillon d'ambre vert émeraude +3",
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de tortue verte',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de tortue à deux têtes',
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Talisman d'arsenal",
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Talisman d'arsenal +1",
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Arsenal de la Grande jarre',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Faveur de l'Arbre-Monde",
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Faveur de l'Arbre-Monde +1",
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Faveur de l'Arbre-Monde +2",
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Sceau scarifié de Radagon',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Sceau meurtri de Radagon',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Sceau scarifié de Marika',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Sceau meurtri de Marika',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Héritage du Fléau des astres',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Héritage de l'épéiste amputée",
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Héritage de l'astrologue",
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Héritage des Deux Doigts',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Héritage de la Divinité extérieure',
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de bouclier draconique',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de bouclier draconique +1',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de bouclier draconique +2',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de pavois draconique',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de dragon magique',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de dragon magique +1',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de dragon magique +2',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de dragon magique +3',
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de dragon de feu',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de dragon de feu +1',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de dragon de feu +2',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de dragon de feu +3',
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de dragon de foudre',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de dragon de foudre +1',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de dragon de foudre +2',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de dragon de foudre +3',
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de dragon sacré',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de dragon sacré +1',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de dragon sacré +2',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Tresse dorée',
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de dragon de perle',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de dragon de perle +1',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de dragon de perle +2',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de dragon de perle +3',
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Corne d'immunité",
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Corne d'immunité +1",
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Corne d'immunité +2",
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Corne de robustesse',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Corne de robustesse +1',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Corne de robustesse +2',
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Corne de focalisation',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Corne de focalisation +1',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Corne de focalisation +2',
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Pendentif bariolé',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Pendentif bariolé +1',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Pendentif bariolé +2',
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Excroissance du Prince de la Mort',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Kyste du Prince de la Mort',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Talisman d'altération",
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de la dague',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Talisman d'épée courbée",
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de la lame double',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de la hache',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman du marteau',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de la lance',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de la lance de cavalerie',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de la griffe',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Talisman d'épée à deux mains",
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de pavois',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman du bouclier perlé',
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Enchevêtrement de riposte',
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Enchevêtrement de lacération',
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman des flèches mordantes',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman des flèches filantes',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman des flèches mordantes (DLC)',
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de tir précis',
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Talisman de l'amalgame sculpté",
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Talisman de l'amas sculpté",
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman en toile des fidèles',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman en toile des ouailles',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Lame de pierre d'éclat primordiale",
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Lune de Nokstella',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Talisman d'ancien seigneur",
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Icône de Radagon',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Poussière d'étoiles chérie",
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Médaillon de cri',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Jarre de compagnie',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de Parfumeur',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Emblème de Caria à filigrane',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Fragment de guerrier-jarre',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Fragment d'Alexander",
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Icône de Godfrey',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Camée de Rellana',
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de pierre brisée',
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de forgeron',
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de la bête divine enragée',
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Talisman de l'Effroyable",
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman du mouflon',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de la danseuse bleue',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Disque vert-de-gris',
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman du scorpion magique',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman du scorpion de feu',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman du scorpion de foudre',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman du scorpion sacré',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman à écaille du Creuset',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman à plume du Creuset',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman à noeud du Creuset',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman à plume raffiné du Creuset',
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de tous les Creusets',
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Lame cornue aux plumes rouges',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Lame cornue aux plumes bleues',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Talisman d'épée rituelle",
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman de bouclier rituel',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Dague pourpre de l'assassin",
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Dague céruléenne de l'assassin",
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Insigne d'épée ailée",
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Insigne d'épée ailée putréfiée",
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Prothèse de Milicent',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Lange sanctechair',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Exultation des adptes de la putréfaction',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Exultation du seigneur du sang',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Exultation de l'ancien",
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Sourire de sainte Trina',
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Lame de miséricorde',
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Camée de pillard',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Corne de l'esprit ancestral",
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Insigne de croisade',
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Bouquet séché',
    inDlc: true,
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Scarabée d'or",
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Scarabée d'argent",
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Fiole de Crepus',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Cape dissimulatrice',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Talisman du chat à longue queue',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Miroir retors de Doigt crochu',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: "Miroir retors d'hôte",
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Malheur de Shabiri',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Malheur de Daedicar',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
  {
    type: 'talisman',
    name: 'Branche sacrificielle',
    imageUrl: '',
    wikiUrl: '',
    locationUrl: '',
  },
];
